In [1]:
import numpy as np
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")

In [2]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
# preprocessing_converting Nominal data_converting String into numeric 

dataset=pd.get_dummies(dataset, drop_first=True, dtype=int)

In [4]:
dataset


age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
#splitting input and output data
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [7]:
independent

age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [9]:
#preparing for the input data in a range usiing Standard scaler

from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
independent=SS.fit_transform(independent)
independent

array([[-1.43876426, -0.45332   , -0.90861367, -1.0105187 ,  1.97058663],
       [-1.50996545,  0.5096211 , -0.07876719,  0.98959079, -0.5074631 ],
       [-0.79795355,  0.38330685,  1.58092576,  0.98959079, -0.5074631 ],
       ...,
       [-1.50996545,  1.0148781 , -0.90861367, -1.0105187 , -0.5074631 ],
       [-1.29636188, -0.79781341, -0.90861367, -1.0105187 , -0.5074631 ],
       [ 1.55168573, -0.26138796, -0.90861367, -1.0105187 ,  1.97058663]])

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
param_grid={ 'fit_intercept':[True,False], 
            'copy_X':[True,False], 
            'n_jobs':[None], 
            'positive':[True,False] }
grid=GridSearchCV(LinearRegression(),param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 8 candidates, totalling 40 fits


GridSearchCV(estimator=LinearRegression(), n_jobs=-1,
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False], 'n_jobs': [None],
                         'positive': [True, False]},
             verbose=3)

In [11]:
#best parameters after tunning
print ("Rscore value for best parameter {}".format(grid.best_params_))

Rscore value for best parameter {'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': True}


In [12]:
results=grid.cv_results_
table=pd.DataFrame.from_dict(results)

In [13]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_copy_X  \
0       0.002305      0.000909         0.000591        0.000358         True   
1       0.002771      0.001310         0.000680        0.000272         True   
2       0.001886      0.000325         0.000875        0.000300         True   
3       0.001900      0.000185         0.000722        0.000148         True   
4       0.002375      0.000395         0.000889        0.000107        False   
5       0.001797      0.000808         0.000484        0.000196        False   
6       0.000964      0.000135         0.000362        0.000054        False   
7       0.000884      0.000186         0.000333        0.000065        False   

  param_fit_intercept param_n_jobs param_positive  \
0                True         None           True   
1                True         None          False   
2               False         None           True   
3               False         None          False   
4                True         None           True   
5                True         None          False   
6               False         None           True   
7               False         None          False   

                                              params  split0_test_score  \
0  {'copy_X': True, 'fit_intercept': True, 'n_job...           0.761482   
1  {'copy_X': True, 'fit_intercept': True, 'n_job...           0.760979   
2  {'copy_X': True, 'fit_intercept': False, 'n_jo...          -0.329938   
3  {'copy_X': True, 'fit_intercept': False, 'n_jo...          -0.329893   
4  {'copy_X': False, 'fit_intercept': True, 'n_jo...           0.761482   
5  {'copy_X': False, 'fit_intercept': True, 'n_jo...           0.760979   
6  {'copy_X': False, 'fit_intercept': False, 'n_j...          -0.329938   
7  {'copy_X': False, 'fit_intercept': False, 'n_j...          -0.329893   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.708782           0.775584           0.731353           0.756751   
1           0.708733           0.775584           0.731367           0.756545   
2          -0.716615          -0.390302          -0.463066          -0.473329   
3          -0.724411          -0.390302          -0.468261          -0.473329   
4           0.708782           0.775584           0.731353           0.756751   
5           0.708733           0.775584           0.731367           0.756545   
6          -0.716615          -0.390302          -0.463066          -0.473329   
7          -0.724411          -0.390302          -0.468261          -0.473329   

   mean_test_score  std_test_score  rank_test_score  
0         0.746790        0.023778                1  
1         0.746642        0.023713                3  
2        -0.474650        0.131711                5  
3        -0.477239        0.134506                7  
4         0.746790        0.023778                1  
5         0.746642        0.023713                3  
6        -0.474650        0.131711                5  
7        -0.477239        0.134506                7

In [14]:
pred=grid.predict(independent)

In [15]:
#finding r2_score value:

from sklearn.metrics import r2_score
r2score=r2_score(dependent,pred)


In [16]:
r2score

0.749694530346479

In [17]:
# save the model
import pickle
pickle.dump(grid,open("multiple_linear_regression_Grid_model.sav",'wb'))

In [18]:
#load the model
loaded_model=pickle.load(open("multiple_linear_regression_Grid_model.sav",'rb'))

In [19]:
#loaded_model.predict([[12,35,0,1,0]])

In [20]:
input=SS.transform([[19,27.900,0,1,0]])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [21]:
input


array([[-1.43876426, -0.45332   , -0.90861367,  0.98959079, -0.5074631 ]])

In [22]:
loaded_model.predict(input)

array([[1776.02540431]])

[CV 4/5] END copy_X=True, fit_intercept=True, n_jobs=None, positive=True;, score=0.731 total time=   0.0s
[CV 4/5] END copy_X=False, fit_intercept=True, n_jobs=None, positive=False;, score=0.731 total time=   0.0s
[CV 1/5] END copy_X=False, fit_intercept=False, n_jobs=None, positive=True;, score=-0.330 total time=   0.0s
[CV 2/5] END copy_X=True, fit_intercept=True, n_jobs=None, positive=True;, score=0.709 total time=   0.0s
[CV 2/5] END copy_X=True, fit_intercept=False, n_jobs=None, positive=True;, score=-0.717 total time=   0.0s
[CV 4/5] END copy_X=True, fit_intercept=False, n_jobs=None, positive=True;, score=-0.463 total time=   0.0s
[CV 1/5] END copy_X=True, fit_intercept=False, n_jobs=None, positive=False;, score=-0.330 total time=   0.0s
[CV 3/5] END copy_X=True, fit_intercept=False, n_jobs=None, positive=False;, score=-0.390 total time=   0.0s
[CV 5/5] END copy_X=True, fit_intercept=False, n_jobs=None, positive=False;, score=-0.473 total time=   0.0s
[CV 3/5] END copy_X=False, f