In [1]:
import pandas as pd
import numpy as np
import matplotlib as plot


In [2]:
dataset=pd.read_csv("CKD.csv")
#dataset

In [3]:
dataset=pd.get_dummies(dataset, drop_first=True, dtype=int)
#dataset

In [4]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
#Split the data
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset[['classification_yes']]

In [6]:
dataset['classification_yes'].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [7]:
#Split the datas for training and test data set
#from sklearn.model_selection import train_test_split
#x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30, random_state=0)
#x_train,x_test

In [8]:
#scale the data to a range using Standard scaler
#from sklearn.preprocessing import StandardScaler
#SS=StandardScaler()
#independent=SS.fit_transform(independent)
#dependent=SS.transform(dependent)


In [9]:
#1. Model creation using GaussianNB 
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB
param_grid={ 'priors':[None], 'var_smoothing':[1e-09]

}

model=GridSearchCV(GaussianNB(),param_grid,refit=True, scoring='f1_weighted', cv=5)

model.fit(independent,dependent)
y_pred=model.predict(independent)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(dependent,y_pred)
print(cm)

from sklearn.metrics import classification_report
clf_report=classification_report(dependent,y_pred)
print (clf_report)

[[149   1]
 [  4 245]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       150
           1       1.00      0.98      0.99       249

    accuracy                           0.99       399
   macro avg       0.98      0.99      0.99       399
weighted avg       0.99      0.99      0.99       399



/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samp

In [10]:
#2. Model creation using BernoulliNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV

param_grid= {
    'alpha':[1.0], 
    'force_alpha':[True], 
    'binarize':[0.0], 
    'fit_prior':[True], 
    'class_prior':[None]
}
model=GridSearchCV(BernoulliNB(),param_grid,refit=True, scoring='f1_weighted', cv=5)

model.fit(independent,dependent)
y_pred=model.predict(independent)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(dependent,y_pred)
print(cm)

from sklearn.metrics import classification_report
clf_report=classification_report(dependent,y_pred)
print (clf_report)

[[149   1]
 [ 19 230]]
              precision    recall  f1-score   support

           0       0.89      0.99      0.94       150
           1       1.00      0.92      0.96       249

    accuracy                           0.95       399
   macro avg       0.94      0.96      0.95       399
weighted avg       0.95      0.95      0.95       399



/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samp

In [11]:
# model creation using MultinomialNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV

param_grid= {
    'alpha':[1.0], 
    'force_alpha':[True], 
    'fit_prior':[True], 
    'class_prior':[None]
}
model=GridSearchCV(MultinomialNB(),param_grid,refit=True, verbose=3, scoring='f1_weighted', cv=5)



model.fit(independent,dependent)
y_pred=model.predict(independent)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(dependent,y_pred)
print(cm)

from sklearn.metrics import classification_report
clf_report=classification_report(dependent,y_pred)
print (clf_report)


Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 1/5] END alpha=1.0, class_prior=None, fit_prior=True, force_alpha=True;, score=0.659 total time=   0.0s
[CV 2/5] END alpha=1.0, class_prior=None, fit_prior=True, force_alpha=True;, score=0.865 total time=   0.0s
[CV 3/5] END alpha=1.0, class_prior=None, fit_prior=True, force_alpha=True;, score=0.914 total time=   0.0s
[CV 4/5] END alpha=1.0, class_prior=None, fit_prior=True, force_alpha=True;, score=0.914 total time=   0.0s
[CV 5/5] END alpha=1.0, class_prior=None, fit_prior=True, force_alpha=True;, score=0.924 total time=   0.0s
[[145   5]
 [ 54 195]]
              precision    recall  f1-score   support

           0       0.73      0.97      0.83       150
           1       0.97      0.78      0.87       249

    accuracy                           0.85       399
   macro avg       0.85      0.87      0.85       399
weighted avg       0.88      0.85      0.85       399



/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samp

In [12]:
#. Model creation using ComplementNB
from sklearn.naive_bayes import ComplementNB
from sklearn.model_selection import GridSearchCV

param_grid= {
    'alpha':[1.0], 
    'force_alpha':[True], 
    'fit_prior':[True], 
    'class_prior':[None],
    
}
model=GridSearchCV(ComplementNB(),param_grid,refit=True, scoring='f1_weighted', cv=5)


model.fit(independent,dependent)
y_pred=model.predict(independent)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(dependent,y_pred)
print(cm)

from sklearn.metrics import classification_report
clf_report=classification_report(dependent,y_pred)
print (clf_report)

[[145   5]
 [ 56 193]]
              precision    recall  f1-score   support

           0       0.72      0.97      0.83       150
           1       0.97      0.78      0.86       249

    accuracy                           0.85       399
   macro avg       0.85      0.87      0.84       399
weighted avg       0.88      0.85      0.85       399



/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samp

In [13]:
#. Model creation using CategoricalNB
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import GridSearchCV

param_grid= {
    'alpha':[1.0], 
    'force_alpha':[True], 
    'fit_prior':[True], 
    'class_prior':[None]
   # 'min_categories':[None]
}
model=GridSearchCV(CategoricalNB(),param_grid,refit=True, verbose=3,scoring='f1_weighted', cv=5)


model.fit(independent,dependent)
y_pred=model.predict(independent)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(dependent,y_pred)
print(cm)

from sklearn.metrics import classification_report
clf_report=classification_report(dependent,y_pred)
print (clf_report)



Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 1/5] END alpha=1.0, class_prior=None, fit_prior=True, force_alpha=True;, score=0.950 total time=   0.0s
[CV 2/5] END alpha=1.0, class_prior=None, fit_prior=True, force_alpha=True;, score=nan total time=   0.0s
[CV 3/5] END alpha=1.0, class_prior=None, fit_prior=True, force_alpha=True;, score=nan total time=   0.0s
[CV 4/5] END alpha=1.0, class_prior=None, fit_prior=True, force_alpha=True;, score=nan total time=   0.0s
[CV 5/5] END alpha=1.0, class_prior=None, fit_prior=True, force_alpha=True;, score=nan total time=   0.0s
[[150   0]
 [  1 248]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       150
           1       1.00      1.00      1.00       249

    accuracy                           1.00       399
   macro avg       1.00      1.00      1.00       399
weighted avg       1.00      1.00      1.00       399



/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anac

In [14]:
#finidng roc_auc score
from sklearn.metrics import roc_auc_score
roc_auc_score=roc_auc_score(dependent, model.predict_proba(independent)[:,1])
print("ROC_AUC_Score={}".format(roc_auc_score))

ROC_AUC_Score=0.9999196787148594
