In [1]:
import numpy as np
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")


In [2]:
#dataset

In [3]:
# 1.convert dataset from string to numerical data

dataset=pd.get_dummies(dataset, drop_first=True, dtype=int)

In [4]:
#dataset

In [5]:
#dataset.columns

In [6]:
# 2. split input and output data
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [7]:
# 3. preprocessing the data in a range

from sklearn.preprocessing import StandardScaler
SS= StandardScaler()
independent = SS.fit_transform(independent)
#dependent = SS.fit_transform(dependent)

independent

array([[-1.43876426, -0.45332   , -0.90861367, -1.0105187 ,  1.97058663],
       [-1.50996545,  0.5096211 , -0.07876719,  0.98959079, -0.5074631 ],
       [-0.79795355,  0.38330685,  1.58092576,  0.98959079, -0.5074631 ],
       ...,
       [-1.50996545,  1.0148781 , -0.90861367, -1.0105187 , -0.5074631 ],
       [-1.29636188, -0.79781341, -0.90861367, -1.0105187 , -0.5074631 ],
       [ 1.55168573, -0.26138796, -0.90861367, -1.0105187 ,  1.97058663]])

In [8]:
# 4. model creation using grid_serach and RandomForestRegressor

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid={'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
            'max_features': ['sqrt', 'log2'],
               'n_estimators': [100,50] }

grid= GridSearchCV(RandomForestRegressor(),param_grid,refit=True,n_jobs=-1,verbose=3)


In [10]:
#5.fit the grid
dependent=dependent.values.ravel()
grid.fit(independent,dependent)
result=grid.cv_results_

Fitting 5 folds for each of 16 candidates, totalling 80 fits


In [11]:
print(" best parameter for the Rscore value : {}".format(grid.best_params_))

 best parameter for the Rscore value : {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}


In [20]:
#6. Finding R2_score value
pred=grid.predict(independent)

from sklearn.metrics import r2_score
r2_score=r2_score(pred,dependent)
r2_score

0.9643906101355286

In [21]:
#displaying the data as a table
table=pd.DataFrame.from_dict(result)
#table


In [22]:
#Save the model

import pickle
pickle.dump(grid,open('finalized_grid_model_random_forest_regressor.sav','wb'))

In [23]:
# load model

loaded_model=pickle.load(open("finalized_grid_model_random_forest_regressor.sav",'rb'))

In [24]:
# scale the input before prediction
input=SS.transform([[19,27.900,0,1,0]])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [25]:
input

array([[-1.43876426, -0.45332   , -0.90861367,  0.98959079, -0.5074631 ]])

In [26]:
result=loaded_model.predict(input)

In [27]:
result


array([1709.55083275])

[CV 3/5] END criterion=squared_error, max_features=sqrt, n_estimators=100;, score=0.863 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_features=log2, n_estimators=100;, score=0.840 total time=   0.1s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, n_estimators=100;, score=0.843 total time=   0.8s
[CV 3/5] END criterion=absolute_error, max_features=log2, n_estimators=50;, score=0.851 total time=   0.4s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt, n_estimators=100;, score=0.780 total time=   0.1s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt, n_estimators=100;, score=0.826 total time=   0.1s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt, n_estimators=50;, score=0.775 total time=   0.1s
[CV 4/5] END criterion=friedman_mse, max_features=log2, n_estimators=100;, score=0.833 total time=   0.1s
[CV 1/5] END criterion=poisson, max_features=sqrt, n_estimators=50;, score=0.855 total time=   0.1s
[CV 4/5] END criterion=poisson, max_features=sqr