In [1]:
import pandas as pd
import numpy as np
import matplotlib as plot

In [2]:
ds=pd.read_csv("Social_Network_Ads.csv")

In [3]:
ds=pd.get_dummies(ds, drop_first=True,dtype=int)

In [4]:
ds.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [5]:
#ds=ds.drop("User ID",axis=1)
#ds

In [6]:
count=ds['Purchased'].value_counts()
count

Purchased
0    257
1    143
Name: count, dtype: int64

In [7]:
indep=ds[['Age', 'EstimatedSalary','Gender_Male']]

#indep

In [8]:
dep=ds[['Purchased']]

#dep

In [9]:
indep.shape

(400, 3)

In [10]:
dep.shape

(400, 1)

In [11]:
#Split for traning set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3, random_state=0)

#x_train,x_test,y_train,y_test

In [12]:
# scale the input dataset for the range using standard scaler
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
x_train=SS.fit_transform(x_train)
x_test=SS.transform(x_test)


In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
param_grid= {'penalty':["l1", "l2", "elasticnet", None],
             'solver': ["lbfgs", "liblinear", "newton-cg", "newton-cholesky", "sag", "saga"]
            }
grid=GridSearchCV(LogisticRegression(),param_grid,refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')
grid.fit(x_train,y_train)


Fitting 5 folds for each of 24 candidates, totalling 120 fits


/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samp

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l1', 'l2', 'elasticnet', None],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='f1_weighted', verbose=3)

In [14]:
results=grid.cv_results_
table=pd.DataFrame.from_dict(results)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.000593      0.000205         0.000000        0.000000   
1        0.002573      0.001574         0.002442        0.001124   
2        0.000152      0.000030         0.000000        0.000000   
3        0.000140      0.000019         0.000000        0.000000   
4        0.000137      0.000009         0.000000        0.000000   
5        0.002232      0.002273         0.002216        0.001227   
6        0.004306      0.003670         0.005425        0.002098   
7        0.001375      0.000418         0.002382        0.001086   
8        0.002686      0.001258         0.001717        0.000535   
9        0.002958      0.001609         0.001850        0.000859   
10       0.001313      0.000585         0.002296        0.001185   
11       0.001344      0.000509         0.002044        0.000875   
12       0.000306      0.000110         0.000000        0.000000   
13       0.000186      0.000081         0.000000        0.000000   
14       0.000210      0.000127         0.000000        0.000000   
15       0.000137      0.000032         0.000000        0.000000   
16       0.000137      0.000043         0.000000        0.000000   
17       0.001662      0.000592         0.000000        0.000000   
18       0.001291      0.000315         0.001501        0.000294   
19       0.001168      0.000584         0.000000        0.000000   
20       0.003404      0.001367         0.002150        0.001126   
21       0.001718      0.000714         0.001322        0.000072   
22       0.001757      0.000686         0.001794        0.000474   
23       0.001058      0.000160         0.001284        0.000039   

   param_penalty     param_solver  \
0             l1            lbfgs   
1             l1        liblinear   
2             l1        newton-cg   
3             l1  newton-cholesky   
4             l1              sag   
5             l1             saga   
6             l2            lbfgs   
7             l2        liblinear   
8             l2        newton-cg   
9             l2  newton-cholesky   
10            l2              sag   
11            l2             saga   
12    elasticnet            lbfgs   
13    elasticnet        liblinear   
14    elasticnet        newton-cg   
15    elasticnet  newton-cholesky   
16    elasticnet              sag   
17    elasticnet             saga   
18          None            lbfgs   
19          None        liblinear   
20          None        newton-cg   
21          None  newton-cholesky   
22          None              sag   
23          None             saga   

                                               params  split0_test_score  \
0                {'penalty': 'l1', 'solver': 'lbfgs'}                NaN   
1            {'penalty': 'l1', 'solver': 'liblinear'}           0.804764   
2            {'penalty': 'l1', 'solver': 'newton-cg'}                NaN   
3      {'penalty': 'l1', 'solver': 'newton-cholesky'}                NaN   
4                  {'penalty': 'l1', 'solver': 'sag'}                NaN   
5                 {'penalty': 'l1', 'solver': 'saga'}           0.804764   
6                {'penalty': 'l2', 'solver': 'lbfgs'}           0.799620   
7            {'penalty': 'l2', 'solver': 'liblinear'}           0.804764   
8            {'penalty': 'l2', 'solver': 'newton-cg'}           0.799620   
9      {'penalty': 'l2', 'solver': 'newton-cholesky'}           0.799620   
10                 {'penalty': 'l2', 'solver': 'sag'}           0.799620   
11                {'penalty': 'l2', 'solver': 'saga'}           0.799620   
12       {'penalty': 'elasticnet', 'solver': 'lbfgs'}                NaN   
13   {'penalty': 'elasticnet', 'solver': 'liblinear'}                NaN   
14   {'penalty': 'elasticnet', 'solver': 'newton-cg'}                NaN   
15  {'penalty': 'elasticnet', 'solver': 'newton-ch...                NaN   
16         {'penalty': 'elasticnet', 'solver': 'sag'}                NaN   
17       

In [15]:
#find the best parameter after tuning
best_parameter=grid.best_params_
print(best_parameter)

{'penalty': 'l1', 'solver': 'saga'}


In [16]:
y_pred=grid.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[79,  6],
       [10, 39]])

In [18]:
from sklearn.metrics import classification_report
classi_report=classification_report(y_test,y_pred)

In [19]:
print(classi_report)

              precision    recall  f1-score   support

           0       0.89      0.93      0.91        85
           1       0.87      0.80      0.83        49

    accuracy                           0.88       134
   macro avg       0.88      0.86      0.87       134
weighted avg       0.88      0.88      0.88       134



In [20]:
#roc_auc_score
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9493397358943578

In [21]:
grid.predict_proba(x_test)[:,1]

array([0.10464598, 0.16237748, 0.18942393, 0.07886046, 0.09360423,
       0.00842529, 0.01551216, 0.69152897, 0.00494733, 0.5284758 ,
       0.03639548, 0.02682575, 0.16404332, 0.36479099, 0.0137137 ,
       0.28730816, 0.27399097, 0.01082304, 0.98669318, 0.0461217 ,
       0.08630736, 0.954475  , 0.2726615 , 0.87621424, 0.00430611,
       0.96686788, 0.0666106 , 0.07144914, 0.18334503, 0.13823713,
       0.01787738, 0.28597478, 0.93811314, 0.15605236, 0.01381332,
       0.00331465, 0.01790963, 0.06366112, 0.02696981, 0.56274137,
       0.06027519, 0.29360282, 0.05025628, 0.04357557, 0.7776428 ,
       0.02384747, 0.27712389, 0.92324478, 0.00918722, 0.859615  ,
       0.9888831 , 0.03829173, 0.1128138 , 0.38352243, 0.98010619,
       0.34687578, 0.07249738, 0.03668966, 0.52197822, 0.00365597,
       0.02235898, 0.94338741, 0.00830356, 0.37042193, 0.00175675,
       0.98257079, 0.03167066, 0.0256193 , 0.22504576, 0.44857202,
       0.51811075, 0.18727878, 0.00982547, 0.28291177, 0.06198

In [22]:
input=SS.transform([[50,20000,0]])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [23]:
res=grid.predict(input)

In [24]:
print("result = {}".format(res))

result = [0]


In [25]:
input=SS.transform([[50,20000,0]])
grid.predict(input)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0])

[CV 5/5] END ............penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 2/5] END penalty=l2, solver=newton-cholesky;, score=0.811 total time=   0.0s
[CV 3/5] END penalty=l2, solver=newton-cholesky;, score=0.682 total time=   0.0s
[CV 1/5] END ....penalty=elasticnet, solver=lbfgs;, score=nan total time=   0.0s
[CV 2/5] END ....penalty=elasticnet, solver=lbfgs;, score=nan total time=   0.0s
[CV 2/5] END penalty=elasticnet, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 3/5] END penalty=elasticnet, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 4/5] END penalty=elasticnet, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 5/5] END penalty=elasticnet, solver=newton-cholesky;, score=nan total time=   0.0s
[CV 3/5] END ......penalty=None, solver=liblinear;, score=nan total time=   0.0s
[CV 5/5] END ......penalty=None, solver=liblinear;, score=nan total time=   0.0s
[CV 1/5] END ....penalty=None, solver=newton-cg;, score=0.805 total time=   0.0s
[CV 